apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  USER_NAME: YWRtaW4=
  PASSWORD: YWRtaW5AMTIz

---

apiVersion: v1
kind: Pod
metadata:
 name: myapp-pod2
 labels:
   app: myapp
   type: front-end
spec:
  containers:
  - name: httpd-container
    image: httpd
  env:
  - name: SECRET_USERNAME
    valueFrom:
      secretKeyRef:
        name: mysecret
        key: user_name
  - name: SECRET_PASSWD
    valueFrom:
      secretKeyRef:
        name: mysecret
        key: PASSWORD
